### ISSUE TITLE
Unable to initiate

### ISSUE THREAD

**Issue by seanemclean** [richardhopton/smartbed-mqtt#6] opened 2023-03-08 17:27 UTC
This looks like a really cool service, so I'm excited to get it open. Running HA on a Pi4, have a Temperpedic King Bed with the sleeptracker configured and working on the same network. After installing and updating config with my login (confirmed accurate), and start the service, I get this:

Using discovered MQTT Host: core-mosquitto
Using discovered MQTT Port: 1883
Using discovered MQTT User: addons
Using discovered MQTT password: <hidden>
info [2023-03-08T17:22:47.339Z] [MQTT] Connecting...
info [2023-03-08T17:22:48.232Z] [MQTT] Connected
error [2023-03-08T17:22:49.018Z] Could not load devices

**Comment by richardhopton** [comment] 2023-03-11 20:43
@seanemclean If you are still experiencing this issue please join the discord so I can help identify the root cause of your issue. If you are no longer getting this issue please close this issue.

**Closed** 2023-03-26 05:41 UTC
